---
apiVersion: v1
kind: Namespace
metadata:
  name: nodejs-app

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: nodejs-app
  labels:
    app: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: paomb/example-app:latest
        ports:
        - containerPort: 3000
---

kind: Service
apiVersion: v1
metadata:
  name: app-balancer
  namespace: nodejs-app
spec:
  type: LoadBalancer
  selector:
    app: myapp
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000



